spring.application.name=BootFinance
spring.datasource.url = jdbc:mysql://localhost:3306/banking
spring.datasource.username=root
spring.datasource.password=andaz1581
spring.datasource.driver-clas-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port = 587
spring.mail.username=anandraj28127@gmail.com
spring.mail.password=mhscnbgotjsaspgo
spring.mail.properties.mail.smto.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.jwt-secret=xjgnNP/MGwkVllA/fR+NGRZtrQQnyyRhOwomZNA6ovrdnG4uQor9uYBfvX
app.jwt-expiration=3600000